// application constanst
const CONSTANTS = {
	TEAM_SIZE: 5,
	PLAYER_AGE: 21,
	MIN_DEFENDERS_COUNT: 2,
	MIN_GOALKEEPER_COUNT: 1,
	MIN_MIDFIELDERS_COUNT: 1,
	MIN_ATTACKERS_COUNT: 1,
	MAX_SAME_COUNTRY_COUNT: 2,
	AREAS_LABEL: 'area',
	COMPETITIONS_LEVEL: 'competitions',
	SUBAREA_LABEL: 'sub_area',
	TEAMS_LABEL: 'teams_list',
	TYPE_ATTACKER: 'Attacker',
	TYPE_GOALKEEPER: 'Goalkeeper',
	TYPE_MIDFIELDER: 'Midfielder',
	TYPE_DEFENDER: 'Defender',
	PLAYERS_TYPE_COUNT: 4,
	ROUTE_TEAMS: 'Teams',
	ROUTE_SQUAD: 'Squad',
	ROUTE_LEAGUES: 'Leagues',
	ROUTE_HOME: 'Home',
	TEAM_ONE: 18,
	TEAM_TWO: 19,
	TEAM_THREE: 17,
	YEARS_IN_MS: 1000 * 60 * 60 * 24 * 365,
};

export default CONSTANTS;
